on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
          library-manager: submit
          compliance: strict
          project-type: library