on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: bojit/platformio-publish@main@v1.0.0
        with:
          token: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}